### ISSUE TITLE
color doesnt change

### ISSUE THREAD

**Issue by Mangeshrex** [rototrash/lite-xl-config#1]
was finding a lite-xl config from long (cuz didnt have time to make own) got yours. and found out that the colors were'nt changing as specified
![screenshot](https://user-images.githubusercontent.com/82205152/171684713-0fbd0cb3-d7de-4e85-8867-db668699bd95.png)
 
you can see in the screenshot that even when i change the config it doesnt load the colors

**Comment by rototrash** [comment]
Do you have the everblush.lua file in the colors directory? 

This also happens when there are errors in this user config file. Try commenting lines 16 and 17 and restarting lite-xl.

PS: you shouldn't be using this!!! It's not the best and I did this with what little time I had. Try using  [TorchedSammy's](https://github.com/TorchedSammy/dotfiles/tree/master/.config%2Flite-xl) config. It much better than mine. 

Thanks for trying this out though. I'm gonna improve this once I get some time, I have exams and shit the next 2 months.

**Comment by Mangeshrex** [comment]
Ok you can close the issue 😸
